build:
  image: docker.gotute.int:5000/node-build
  commands:
    - npm install
    - node node_modules/bower/bin/bower install --allow-root
    - node ./node_modules/gulp/bin/gulp.js build

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: deployment
    username: drone

